name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  install:
    name: 'Install packages'
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && (github.ref == 'refs/heads/master' || github.event.pull_request.draft == false) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bootstrap lerna
        run: yarn lerna bootstrap --force-local

  lint:
    name: 'Lint project'
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lerna run lint --stream

  unit_test:
    name: 'Unit tests'
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn lerna run test:ci --stream

  build:
    name: 'Build project'
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn lerna run build:dist --stream --scope @ertrzyiks/graph-utils

  release:
    name: 'Update website'
    if: github.ref == 'refs/heads/master'
    needs: [install, unit_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bootstrap lerna
        run: yarn lerna bootstrap --force-local

      - name: Rebuild website
        run: yarn lerna run build:dist --stream --scope website

      - name: Publish website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/website/public
          user_name: 'Automateusz'
          user_email: 'bot@ertrzyiks.me'

